name: Multi-Platform Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  build-android:
#    name: Build Android APK
#    runs-on: windows-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: stable
#
#      - name: Install Dependencies
#        run: flutter pub get
#
#      - name: Build Android APK
#        run: flutter build apk --release
#
#      - name: Upload APK Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: android-apk
#          path: build/app/outputs/flutter-apk/app-release.apk

#  build-ios:
#    name: Build iOS App
#    runs-on: macos-latest
#    needs: build-android
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: stable
#
#      - name: Install Dependencies
#        run: flutter pub get
#
#      - name: Build iOS App
#        run: flutter build ipa --release
#
#      - name: Upload IPA Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ios-ipa
#          path: build/ios/ipa/*.ipa
#
  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    needs: build-ios

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: build/macos/Build/Products/Release/*.app

  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    needs: build-macos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release/*.exe
