name: Build and Release Windows App

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags like v1.0.0

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Fetch dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Build the Windows release executable
      - name: Build Windows App
        run: flutter build windows --release

      # Step 5: Upload the build artifact
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-App
          path: build/windows/runner/Release/*.exe

  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Upload to GitHub Release
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
