name: "Build & Release"
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies for Windows
        run: |
          choco install visualstudio2022buildtools visualstudio2022-workload-vctools -y
          flutter doctor

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release --verbose

      - name: Verify Build Artifacts
        run: ls build/windows/runner/Release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release/*.exe

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/runner/Release/*.exe"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
